# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asimi < Formula
  desc "AI-powered CLI assistant with container support - safe, opinionated coding agent"
  homepage "https://github.com/afittestide/asimi-cli"
  version "0.4.2"
  license "MIT"

  depends_on "podman" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.4.2/asimi_0.4.2_darwin_amd64.tar.gz"
      sha256 "c77ebadbd02e59c8266349f322905cbded1da64cf55b70d68d6c3cd65bbbdb1f"

      def install
        bin.install "asimi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.4.2/asimi_0.4.2_darwin_arm64.tar.gz"
      sha256 "6229e548b08b451e780f91270b1e97cc6f415e769a44972058ee9a1ee064040e"

      def install
        bin.install "asimi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.4.2/asimi_0.4.2_linux_amd64.tar.gz"
      sha256 "d463fdcc4de59e8ce63f16b1f258fe009d1f35583287f9f67ff887fcf97a3f98"
      def install
        bin.install "asimi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.4.2/asimi_0.4.2_linux_arm64.tar.gz"
      sha256 "50ecf80f127fa98ada957cebb069233a8e9b97d95aa275d8e508246b9654dffa"
      def install
        bin.install "asimi"
      end
    end
  end

  def caveats
    <<~EOS
      Asimi requires Podman for containerized shell execution.
      Install it with: brew install podman

      For configuration, see: https://github.com/afittestide/asimi-cli
    EOS
  end

  test do
    system "#{bin}/asimi", "--version"
  end
end
