# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asimi < Formula
  desc "AI-powered CLI assistant with container support - safe, opinionated coding agent"
  homepage "https://github.com/afittestide/asimi-cli"
  version "0.7.0"
  license "MIT"

  depends_on "podman" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.7.0/asimi_0.7.0_darwin_amd64.tar.gz"
      sha256 "5f4b4785618047268792a159836dc61aa161b7199db49c9e0de388374af0bba9"

      define_method(:install) do
        bin.install "asimi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.7.0/asimi_0.7.0_darwin_arm64.tar.gz"
      sha256 "42c2cd2281482cdcd676d144c3f743dbf75569fd9ff3217c15fb3a973eb91b42"

      define_method(:install) do
        bin.install "asimi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.7.0/asimi_0.7.0_linux_amd64.tar.gz"
      sha256 "f2f1574c55b626d58c1a602df630661039d36052ed1f2163ad05f1101823311a"
      define_method(:install) do
        bin.install "asimi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.7.0/asimi_0.7.0_linux_arm64.tar.gz"
      sha256 "9ca173690c16a50a9ca587e0ace2fbecbfc5935fe10383fc1977d8072323cc0c"
      define_method(:install) do
        bin.install "asimi"
      end
    end
  end

  def caveats
    <<~EOS
      Asimi requires Podman for containerized shell execution.
      Install it with: brew install podman

      For configuration, see: https://github.com/afittestide/asimi-cli
    EOS
  end

  test do
    system "#{bin}/asimi", "--version"
  end
end
