# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asimi < Formula
  desc "AI-powered CLI assistant with container support - safe, opinionated coding agent"
  homepage "https://github.com/afittestide/asimi-cli"
  version "0.10.1"
  license "MIT"

  depends_on "podman" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.10.1/asimi_0.10.1_darwin_amd64.tar.gz"
      sha256 "48785b08c2fae8fd9591a44657cfdc20d67e87d41887d77338bf46d75a399347"

      define_method(:install) do
        bin.install "asimi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.10.1/asimi_0.10.1_darwin_arm64.tar.gz"
      sha256 "fa30073b1fe07a7b424170b8c1dfa2eb7cce34465202460f3edb97f788001d41"

      define_method(:install) do
        bin.install "asimi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.10.1/asimi_0.10.1_linux_amd64.tar.gz"
      sha256 "efcdf13a7f3eb2cd303b65eef3084f1b4d2516f90e1c924c9b89ea64b9ae0b79"
      define_method(:install) do
        bin.install "asimi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afittestide/asimi-cli/releases/download/v0.10.1/asimi_0.10.1_linux_arm64.tar.gz"
      sha256 "97ef8a7f1174016700919f095b01e0e8fb1ff6add2a89bc06b1a19bd770c2499"
      define_method(:install) do
        bin.install "asimi"
      end
    end
  end

  def caveats
    <<~EOS
      Asimi requires Podman for containerized shell execution.
      Install it with: brew install podman

      For configuration, see: https://github.com/afittestide/asimi-cli
    EOS
  end

  test do
    system "#{bin}/asimi", "--version"
  end
end
